### ISSUE TITLE
mingw32-make: *** No rule to make target '../poly-split-master/poly-split.pro', needed by 'Makefile'.  Stop.

### ISSUE THREAD

**Issue by andrericss** [dhmhd/poly-split#1]
I'm receiving this following error while trying to build the project:

"mingw32-make: **\* No rule to make target '../poly-split-master/poly-split.pro', needed by 'Makefile'.  Stop.
10:35:52: The process "C:\Qt\Qt5.3.2\Tools\mingw482_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project poly-split (kit: Desktop Qt 5.3 MinGW 32bit)
When executing step "Make""

How to solve it?

Thank you in advance!

**Comment by dhmhd** [comment]
As the matter of fact, I never try to build it under Windows. But right now
I have cloned the project from git, opened it with Qt (5.7.0) creator and
successfully build and run the application. So, I think that problem with
your Qt configuration.

2016-09-28 16:41 GMT+03:00 andrericss notifications@github.com:

**Comment by andrericss** [comment]
I executed it in Ubuntu 16.04.01 and all worked perfectly. Thank you!
