### ISSUE TITLE
Question: how to build this in VisualStudio on widows

### ISSUE THREAD

**Issue by michaldengusiak** [dhmhd/poly-split#2]
I just come across your code and looks great, 
However, I am unable to build this in Visual Studio... can you share your build folder or provide some advice?

**Comment by dhmhd** [comment]
I've never tried to build a Qt project in VS. I'll check it as soon as I can...

**Comment by dhmhd** [comment]
There is a [plugin for Visual Studio](https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStudioTools2019) that can convert Qt projects (.pro) to Visual Studio projects (.vsxproj). You can find poly-split.vcxproj and poly-split.sln in repo. I successfully build a program with:

- Microsoft Visual Studio Community 2019 (16.5.4);
- Microsoft C/C++ compiler (19.25.28614);
- Qt Visual Studio Tools (2.4.3);
- Qt5 (5.14.2) (build tools from C:\Qt\Qt5.14.2\5.14.2\msvc2017_64).

P.S. _Qt Visual Studio Tools_ must be configured before using: setup Qt build tools path in Visual Studio (Extentions>QT VS Tool>QT Options).
