### ISSUE TITLE
about successful compilation of program

### ISSUE THREAD

**Issue by Kalpesh-jadhav09** [dhmhd/poly-split#4]
hey im tryng to compile and run the program but its giving me some import error 
plz can you make changes in the readme file for the necessary dependencies which 
are needed for the running the algorithm!

Regards
Kalpesh Jadhav
(student)

**Comment by dhmhd** [comment]
I won't be able to look at it urgently, maybe I can find some time during this or next weekend. The program only uses Qt and the standard library. If Qt is installed, it's quite strange that you're experiencing issues. Provide the import error message here.

**Comment by SohanShinde4** [comment]
> I won't be able to look at it urgently, maybe I can find some time during this or next weekend. The program only uses Qt and the standard library. If Qt is installed, it's quite strange that you're experiencing issues. Provide the import error message here.

Error Message :
PS D:\poly-split-master> g++ main.cpp
In file included from mainwindow.h:5:0,
                 from main.cpp:1:
./renderarea.h:4:19: fatal error: QWidget: No such file or directory
 #include <QWidget>
                                  ^
compilation terminated.

I have installed qt from this url "https://download.qt.io/new_archive/qt/5.3/5.3.2/qt-opensource-windows-x86-winrt-5.3.2.exe"

**Comment by dhmhd** [comment]
Please ensure that you have Qt (version 5.3.2 or later, as specified in the requirements section) installed on your development machine. Run the following command:

```bash
qmake poly-split.pro
```

Additionally, note that this project not only provides a library but also includes a demo GUI application. Consequently, you will need a DE to execute the last one. For simplicity, use a specialized IDE - QtCreator (https://doc.qt.io/qtcreator/).

If you don't want to install QtCreator, you can use VisualStudio or maybe VisualStudioCode. Project file poly-split.vcxproj is also in root directory.
